In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

from sklearn.preprocessing import scale
import sklearn.linear_model as skl_lm
from sklearn.metrics import mean_squared_error, r2_score
import statsmodels.api as sm
import statsmodels.formula.api as smf

In [2]:
import pandas as pd
df = pd.read_csv('Carseats.csv',sep=',',na_values=['?'])
df

,Unnamed: 0,Sales,CompPrice,Income,Advertising,Population,Price,ShelveLoc,Age,Education,Urban,US
0,1,9.50,138,73,11,276,120,Bad,42,17,Yes,Yes
1,2,11.22,111,48,16,260,83,Good,65,10,Yes,Yes
2,3,10.06,113,35,10,269,80,Medium,59,12,Yes,Yes
3,4,7.40,117,100,4,466,97,Medium,55,14,Yes,Yes
4,5,4.15,141,64,3,340,128,Bad,38,13,Yes,No
...,...,...,...,...,...,...,...,...,...,...,...,...
395,396,12.57,138,108,17,203,128,Good,33,14,Yes,Yes
396,397,6.14,139,23,3,37,120,Medium,55,11,No,Yes
397,398,7.41,162,26,12,368,159,Medium,40,18,Yes,Yes
398,399,5.94,100,79,7,284,95,Bad,50,12,Yes,Yes
399,400,9.71,134,37,0,27,120,Good,49,16,Yes,Yes

In [3]:
#remove columns not needed
df1 = df.drop(columns=['ShelveLoc'])
df1

,Unnamed: 0,Sales,CompPrice,Income,Advertising,Population,Price,Age,Education,Urban,US
0,1,9.50,138,73,11,276,120,42,17,Yes,Yes
1,2,11.22,111,48,16,260,83,65,10,Yes,Yes
2,3,10.06,113,35,10,269,80,59,12,Yes,Yes
3,4,7.40,117,100,4,466,97,55,14,Yes,Yes
4,5,4.15,141,64,3,340,128,38,13,Yes,No
...,...,...,...,...,...,...,...,...,...,...,...
395,396,12.57,138,108,17,203,128,33,14,Yes,Yes
396,397,6.14,139,23,3,37,120,55,11,No,Yes
397,398,7.41,162,26,12,368,159,40,18,Yes,Yes
398,399,5.94,100,79,7,284,95,50,12,Yes,Yes
399,400,9.71,134,37,0,27,120,49,16,Yes,Yes

In [4]:
#identify missing values
df1.isnull().sum(axis=0)

Unnamed: 0     0
Sales          0
CompPrice      0
Income         0
Advertising    0
Population     0
Price          0
Age            0
Education      0
Urban          0
US             0
dtype: int64

In [5]:
#remove rows with missing values
df2 = df1.dropna(axis=0)
df2

,Unnamed: 0,Sales,CompPrice,Income,Advertising,Population,Price,Age,Education,Urban,US
0,1,9.50,138,73,11,276,120,42,17,Yes,Yes
1,2,11.22,111,48,16,260,83,65,10,Yes,Yes
2,3,10.06,113,35,10,269,80,59,12,Yes,Yes
3,4,7.40,117,100,4,466,97,55,14,Yes,Yes
4,5,4.15,141,64,3,340,128,38,13,Yes,No
...,...,...,...,...,...,...,...,...,...,...,...
395,396,12.57,138,108,17,203,128,33,14,Yes,Yes
396,397,6.14,139,23,3,37,120,55,11,No,Yes
397,398,7.41,162,26,12,368,159,40,18,Yes,Yes
398,399,5.94,100,79,7,284,95,50,12,Yes,Yes
399,400,9.71,134,37,0,27,120,49,16,Yes,Yes

In [1]:
#remove columns with missing values
df3=df1.dropna(axis=1)
df3

NameError: name 'df1' is not defined

In [7]:
#only drop rows where all columns are NaN
df4=df1.dropna(how='all')
df4

,Unnamed: 0,Sales,CompPrice,Income,Advertising,Population,Price,Age,Education,Urban,US
0,1,9.50,138,73,11,276,120,42,17,Yes,Yes
1,2,11.22,111,48,16,260,83,65,10,Yes,Yes
2,3,10.06,113,35,10,269,80,59,12,Yes,Yes
3,4,7.40,117,100,4,466,97,55,14,Yes,Yes
4,5,4.15,141,64,3,340,128,38,13,Yes,No
...,...,...,...,...,...,...,...,...,...,...,...
395,396,12.57,138,108,17,203,128,33,14,Yes,Yes
396,397,6.14,139,23,3,37,120,55,11,No,Yes
397,398,7.41,162,26,12,368,159,40,18,Yes,Yes
398,399,5.94,100,79,7,284,95,50,12,Yes,Yes
399,400,9.71,134,37,0,27,120,49,16,Yes,Yes

In [8]:
#drop rows that have less than 3 real values 
df5=df1.dropna(thresh=4)
df5

,Unnamed: 0,Sales,CompPrice,Income,Advertising,Population,Price,Age,Education,Urban,US
0,1,9.50,138,73,11,276,120,42,17,Yes,Yes
1,2,11.22,111,48,16,260,83,65,10,Yes,Yes
2,3,10.06,113,35,10,269,80,59,12,Yes,Yes
3,4,7.40,117,100,4,466,97,55,14,Yes,Yes
4,5,4.15,141,64,3,340,128,38,13,Yes,No
...,...,...,...,...,...,...,...,...,...,...,...
395,396,12.57,138,108,17,203,128,33,14,Yes,Yes
396,397,6.14,139,23,3,37,120,55,11,No,Yes
397,398,7.41,162,26,12,368,159,40,18,Yes,Yes
398,399,5.94,100,79,7,284,95,50,12,Yes,Yes
399,400,9.71,134,37,0,27,120,49,16,Yes,Yes

In [9]:
from sklearn.impute import SimpleImputer 
import numpy as np
imr = SimpleImputer(missing_values= np.nan, strategy='most_frequent')
imr = imr.fit(df1.values)
df_imputed = imr.transform(df1)
df_imputed = pd.DataFrame(df_imputed,columns=df1.columns)

C:\Users\jenni\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2732: UserWarning: X has feature names, but SimpleImputer was fitted without feature names
  warnings.warn(

In [10]:
df_imputed.isnull().sum(axis=0)

Unnamed: 0     0
Sales          0
CompPrice      0
Income         0
Advertising    0
Population     0
Price          0
Age            0
Education      0
Urban          0
US             0
dtype: int64

In [11]:
df2

,Unnamed: 0,Sales,CompPrice,Income,Advertising,Population,Price,Age,Education,Urban,US
0,1,9.50,138,73,11,276,120,42,17,Yes,Yes
1,2,11.22,111,48,16,260,83,65,10,Yes,Yes
2,3,10.06,113,35,10,269,80,59,12,Yes,Yes
3,4,7.40,117,100,4,466,97,55,14,Yes,Yes
4,5,4.15,141,64,3,340,128,38,13,Yes,No
...,...,...,...,...,...,...,...,...,...,...,...
395,396,12.57,138,108,17,203,128,33,14,Yes,Yes
396,397,6.14,139,23,3,37,120,55,11,No,Yes
397,398,7.41,162,26,12,368,159,40,18,Yes,Yes
398,399,5.94,100,79,7,284,95,50,12,Yes,Yes
399,400,9.71,134,37,0,27,120,49,16,Yes,Yes

In [12]:
size_mapping = {'No': 0,
                'Yes': 1}

df2['US'] = df2['US'].map(size_mapping)
df2

,Unnamed: 0,Sales,CompPrice,Income,Advertising,Population,Price,Age,Education,Urban,US
0,1,9.50,138,73,11,276,120,42,17,Yes,1
1,2,11.22,111,48,16,260,83,65,10,Yes,1
2,3,10.06,113,35,10,269,80,59,12,Yes,1
3,4,7.40,117,100,4,466,97,55,14,Yes,1
4,5,4.15,141,64,3,340,128,38,13,Yes,0
...,...,...,...,...,...,...,...,...,...,...,...
395,396,12.57,138,108,17,203,128,33,14,Yes,1
396,397,6.14,139,23,3,37,120,55,11,No,1
397,398,7.41,162,26,12,368,159,40,18,Yes,1
398,399,5.94,100,79,7,284,95,50,12,Yes,1
399,400,9.71,134,37,0,27,120,49,16,Yes,1

In [13]:
size_mapping = {'No': 0,
                'Yes': 1}

df2['Urban'] = df2['Urban'].map(size_mapping)
df2

,Unnamed: 0,Sales,CompPrice,Income,Advertising,Population,Price,Age,Education,Urban,US
0,1,9.50,138,73,11,276,120,42,17,1,1
1,2,11.22,111,48,16,260,83,65,10,1,1
2,3,10.06,113,35,10,269,80,59,12,1,1
3,4,7.40,117,100,4,466,97,55,14,1,1
4,5,4.15,141,64,3,340,128,38,13,1,0
...,...,...,...,...,...,...,...,...,...,...,...
395,396,12.57,138,108,17,203,128,33,14,1,1
396,397,6.14,139,23,3,37,120,55,11,0,1
397,398,7.41,162,26,12,368,159,40,18,1,1
398,399,5.94,100,79,7,284,95,50,12,1,1
399,400,9.71,134,37,0,27,120,49,16,1,1

In [14]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

from sklearn.preprocessing import scale
import sklearn.linear_model as skl_lm
from sklearn.metrics import mean_squared_error, r2_score
import statsmodels.api as sm
import statsmodels.formula.api as smf

In [15]:
advertising = pd.read_csv('Carseats.csv', usecols=[1,6,10,11])
display(advertising)
advertising_X = advertising.loc[:,['Price','Urban','US']]
advertising_Y = advertising.loc[:,['Sales']]
display(advertising_X)
display(advertising_Y)

     Sales  Price Urban   US
0     9.50    120   Yes  Yes
1    11.22     83   Yes  Yes
2    10.06     80   Yes  Yes
3     7.40     97   Yes  Yes
4     4.15    128   Yes   No
..     ...    ...   ...  ...
395  12.57    128   Yes  Yes
396   6.14    120    No  Yes
397   7.41    159   Yes  Yes
398   5.94     95   Yes  Yes
399   9.71    120   Yes  Yes

[400 rows x 4 columns]

     Price Urban   US
0      120   Yes  Yes
1       83   Yes  Yes
2       80   Yes  Yes
3       97   Yes  Yes
4      128   Yes   No
..     ...   ...  ...
395    128   Yes  Yes
396    120    No  Yes
397    159   Yes  Yes
398     95   Yes  Yes
399    120   Yes  Yes

[400 rows x 3 columns]

     Sales
0     9.50
1    11.22
2    10.06
3     7.40
4     4.15
..     ...
395  12.57
396   6.14
397   7.41
398   5.94
399   9.71

[400 rows x 1 columns]